[package]
name = "game"
version = "0.1.0"
edition = "2021"


[dependencies]
glfw.workspace = true
env_logger.workspace = true
log.workspace = true
gl_bindings.workspace = true
anyhow.workspace = true
glam.workspace = true
fontdue.workspace = true
gltf.workspace = true

[lints]
workspace = true
